### ISSUE TITLE
问个题外话，请问traceroute是怎么做到直接访问goole Map的呀

### ISSUE THREAD

**Issue by moxixuan** [17mon/china_ip_list#17]
您好，我发现流量监控里面有个goole map，大概10月前的那段时间不是直接访问不了吗？请求这是怎么做到的，我没有找到traceroute的相关源码

thanks

**Comment by lilydjwg** [comment]
ditu.google.cn

**Comment by moxixuan** [comment]
> 
> 
> ditu.google.cn

![3~C%)S4Z2{EMZGZ 1W} 4TI](https://user-images.githubusercontent.com/19483437/68126922-ca1e6680-ff4f-11e9-83e1-b567cbe3dd16.png)

我这里打开会跳转到这个的哦，难道跟地区有关？我这里是东莞

**Comment by lilydjwg** [comment]
打开首页跳转不代表资源页面也跳转。

**Comment by moxixuan** [comment]
> 
> 
> 打开首页跳转不代表资源页面也跳转。

soga,thank you so much
