### ISSUE TITLE
可否在丢失部分精度的情况下进一步压缩列表

### ISSUE THREAD

**Issue by SilverBut** [17mon/china_ip_list#2]
假设一部分国内IP为：

> 1.2.3.0-1.2.31.255
> 1.2.33.0-1.2.255.255

这两条是不是可以考虑合并为一条

> 1.2.3.0-1.2.255.255

**Comment by CNMan** [comment]
可以给ocserv搞的200行以内版本: https://github.com/CNMan/ocserv-cn-no-route
目前版本 640493824 IPs，扩大范围以后日常变动基本可忽略，一年更新一两次就行

**Comment by 1265578519** [comment]
@CNMan 楼上被你删了

**Comment by SilverBut** [comment]
@1265578519 用心观察下，不要xjb down
