### ISSUE TITLE
处理数据出错

### ISSUE THREAD

**Issue by yiguihai** [17mon/china_ip_list#22]
早上更新数据ipset报错，查到了以下错误。
https://github.com/17mon/china_ip_list/blob/f38f83b1cca8ad5a1fe6b4b569c36d8b7056397b/china_ip_list.txt#L2089
https://github.com/17mon/china_ip_list/blob/f38f83b1cca8ad5a1fe6b4b569c36d8b7056397b/china_ip_list.txt#L2090
https://github.com/17mon/china_ip_list/blob/f38f83b1cca8ad5a1fe6b4b569c36d8b7056397b/china_ip_list.txt#L2092
用正则处理一下数据更好

**Comment by IceCodeNew** [comment]
附议，希望能把文件处理干净再发布。
我自己是已经更新了处理文件的代码，正确处理异常，所以也不怕下次再有这次的问题了。

**Comment by yiguihai** [comment]
已解决
