### ISSUE TITLE
我的ip是112.250.*.*，为什么没有啊？

### ISSUE THREAD

**Issue by lukemin** [17mon/china_ip_list#23]
我的ip是112.250.*.*，为什么没有啊？ 最多才到112.224开头

**Comment by Wgaham** [comment]
112.250.0.0/12包含在112.224.0.0/11地址段内

**Comment by Wgaham** [comment]
> 我的ip是112.250._._，为什么没有啊？ 最多才到112.224开头

112.250.0.0/12包含在112.224.0.0/11地址段内

**Comment by lukemin** [comment]
明白了，谢谢。
