### ISSUE TITLE
这份列表是从总的IP数据库内解析出来的吗？

### ISSUE THREAD

**Issue by nevermoreluo** [17mon/china_ip_list#3]
我这边已经有了一份IPIP.net 的账号

下载了一个数据库 里面充斥着这样的信息
000.000.000.000	000.255.255.255	保留地址	保留地址	*	*	*	*
001.000.000.000	001.000.000.255	APNIC	APNIC	*	apnic.net	*	*
001.000.001.000	001.000.003.255	中国	福建	*	*	电信	*

能给提一些思路 大概怎样 转化为 
1.0.1.0/24 这样的信息么？

**Comment by wmacjnpc** [comment]
![stats_g](https://user-images.githubusercontent.com/33451921/34307520-842b4746-e783-11e7-9b68-c1f517d66650.gif)
[favicon-96x96.pdf](https://github.com/17mon/china_ip_list/files/1583150/favicon-96x96.pdf)

**Comment by 17mon** [comment]
@nevermoreluo  你搜索下 CIDR
