### ISSUE TITLE
/24转换-格式

### ISSUE THREAD

**Issue by 1265578519** [17mon/china_ip_list#31]
[china_ip_list.txt](https://github.com/17mon/china_ip_list/files/6305965/china_ip_list.txt)

**Comment by IceCodeNew** [comment]
自己写个 python 脚本分分钟的事……
我这里有现成的转换好的文件：

**Comment by 0x0004** [comment]
> 自己写个 python 脚本分分钟的事…… 我这里有现成的转换好的文件： https://www.github.com/IceCodeNew/4Share/tree/master/Proxifier%2Fip_list_1.txt
> 
> (一共分成6-7个文件，其他的自己去同目录下翻）

能不能有个汇总文件

**Comment by IceCodeNew** [comment]
> > 自己写个 python 脚本分分钟的事…… 我这里有现成的转换好的文件： [github.com/IceCodeNew/4Share/tree/master/Proxifier%2Fip_list_1.txt](https://www.github.com/IceCodeNew/4Share/tree/master/Proxifier%2Fip_list_1.txt)
> > (一共分成6-7个文件，其他的自己去同目录下翻）
> 
> 能不能有个汇总文件

https://raw.githubusercontent.com/IceCodeNew/4Share/master/geoip_china/china_ip_list.txt

我要提醒你这个列表已经不是纯粹从这个项目转换得到的了。主要是由这个项目和 https://github.com/felixonmars/chnroutes-alike 合并而成，排除了一些 geolocation 不属于中国但是直连无障碍且速度不错的 IP 地址。
列表可能不适合所有人，不喜欢就自己折腾。

**Comment by 1265578519** [comment]
是的。。所以还是最纯粹的china_ip_list.txt 比较好
