### ISSUE TITLE
ip库有大量的相邻CIDR网段，你是否应该优化下？

### ISSUE THREAD

**Issue by 1265578519** [17mon/china_ip_list#44]
ip库有大量的相邻CIDR网段，你是否应该优化下？
```
111.112.0.0/14
111.116.0.0/15
111.118.200.0/23
111.118.202.0/24
```

例如4条CIDR应当合并如下，此时应该只为2条
```
111.112.0.0-111.117.255.255
111.118.200.0-111.118.202.255
```

**Comment by lilydjwg** [comment]
这是咋合并的？下边那两个根本不是网段啊，咋用呢？

**Comment by SeaHOH** [comment]
> 这是咋合并的？下边那两个根本不是网段啊，咋用呢？

习惯了，包容下。毕竟砖业人士，上个月还判人老外的项目死刑呢。

**Comment by 1265578519** [comment]
合并成/13的话，转换数组为111.112.0.0-111.119.255.255，ip地址范围不一致，所以无法进行合并
