### ISSUE TITLE
请求增加其他地区的列表

### ISSUE THREAD

**Issue by Chenyao2333** [17mon/china_ip_list#5]
请求增加香港/台湾地区的列表

**Comment by paulgao** [comment]
意义是什么？

**Comment by paulgao** [comment]
越做越复杂了，我们想想别的方案吧。。。

**Comment by zhufengme** [comment]
实际上，这是个出口选择以及dns的技巧问题，而不是IP库的问题。如果你将特定域名的DNS解析设置到香港的DNS服务器上，就会命中香港的CDN服务。最有效的例子就是一些大公司的网站，如Google等。

进一步讲，如果你的需求只是科学上网，出口应该设置在低延迟的亚洲国家，而不是设置到美国，这样实际上是低效的。

**Comment by Chenyao2333** [comment]
@zhufengme 挺有道理的，谢谢提醒(｡･∀･)ﾉﾞ
