### ISSUE TITLE
请问下为什么ipip.net上显示中国有3.9E个ip,而这个上面只有3.4E不到？

### ISSUE THREAD

**Issue by breeze9512** [17mon/china_ip_list#7]
RT

**Comment by zhufengme** [comment]
5、为减少条目数量，国内外的运营商骨干网部分 IP 均可能会做模糊化处理，但不影响正常使用。

**Comment by breeze9512** [comment]
那再请问下，贵司如何定义骨干网？仅中国的骨干网IP为何会有5000W，而whois上标注有backbone的中国IP只有几十万？小白不太懂，求专业人事解答啊，谢谢啦~

**Comment by paulgao** [comment]
1、IPIP 的网页上有注明：按 IP 地址拥有量的国家排序（前二十名，中国包含港澳台）；
2、这里的 CHINA 应该是指不包括港澳台的部分。

**Comment by paulgao** [comment]
大体是对的，具体数字没怎么看。
